"""add_voice_summary_embedding

Revision ID: 4848eaa0f8a2
Revises: 0003
Create Date: 2026-06-23 12:14:28.340897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '4848eaa0f8a2'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapters', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chapters', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chapters', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('chapters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companion_chat_messages', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companion_chat_messages', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companion_chat_messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companion_chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('companion_chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_embeddings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document_embeddings', 'doc_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document_embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('document_embeddings', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('document_embeddings', 'embedding',
               existing_type=Vector(384),
               nullable=False)
    op.alter_column('document_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_doc_embeddings_vector', table_name='document_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('generation_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('generation_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('generation_logs', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'claude-sonnet-4-20250514'::character varying"))
    op.alter_column('generation_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('generation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'target_chapters',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scriptures', 'testament',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sermons', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sermons', 'source_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sermons', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('sermons', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sermons', 'phrases_added',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sermons', 'testimonies_suggested',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sermons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('testimonies', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('testimonies', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('testimonies', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('testimonies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('testimonies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('voice_profiles', sa.Column('voice_summary_embedding', Vector(384), nullable=True))
    op.alter_column('voice_profiles', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('voice_profiles', 'onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('voice_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_versions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('voice_versions', 'trigger',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('voice_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'voice_versions', 'chapters', ['chapter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_versions', type_='foreignkey')
    op.alter_column('voice_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_versions', 'trigger',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('voice_versions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('voice_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_profiles', 'onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('voice_profiles', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('voice_profiles', 'voice_summary_embedding')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('testimonies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('testimonies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('testimonies', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('testimonies', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('testimonies', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sermons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sermons', 'testimonies_suggested',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sermons', 'phrases_added',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sermons', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sermons', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('sermons', 'source_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sermons', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scriptures', 'testament',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('projects', 'target_chapters',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('projects', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('generation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('generation_logs', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'claude-sonnet-4-20250514'::character varying"))
    op.alter_column('generation_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('generation_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_doc_embeddings_vector', 'document_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('document_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_embeddings', 'embedding',
               existing_type=Vector(384),
               nullable=True)
    op.alter_column('document_embeddings', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('document_embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('document_embeddings', 'doc_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document_embeddings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companion_chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companion_chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('companion_chat_messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companion_chat_messages', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companion_chat_messages', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chapters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapters', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('chapters', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chapters', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
